#:schema https://docs.jj-vcs.dev/latest/config-schema.json
[revset-aliases]
"tr" = "trunk()"

[ui]
default-command = "log"
editor = "jj-kak --editor"

[templates]
commit_trailers = '''
format_signed_off_by_trailer(self)
++ if(
  !trailers.contains_key("Change-Id"),
  format_gerrit_change_id_trailer(self)
)
'''

duplicate_description = '''
concat(
  description.trim_end(),
  "\n\n(cherry picked from commit ",
  commit_id,
  ")\n"
)
'''

[aliases]
n = ["new"]
squ = ["squash"]
aban = ["abandon"]
push = ["git", "push"]
up = ["git", "push"]
dup = ["duplicate"]
gup = ["gerrit", "upload"]

kak = ["util", "exec", "--", "jj-kak"]
tip = ["util", "exec", "--", "jj-tip"]
adv = ["util", "exec", "--", "jj-advance"]
advance = ["util", "exec", "--", "jj-advance"]

[git]
# Prevent pushing work in progress or anything explicitly labeled "private"
private-commits = "description('wip:*') | description('private:*')"

[snapshot]
max-new-file-size = 1255007
