# kakoune configuration

evaluate-commands %sh{
    if [[ "$kak_version" < "v2022.10.31" ]]; then
        echo "source ${kak_config}/kakrc.old"
    else
        echo "source ${kak_config}/kakrc.v2022.10.31"
    fi
}
