# kakoune configuration

evaluate-commands %sh{
    if [[ "$kak_version" == "unknown" ]]; then
        echo "source ${kak_config}/kakrc.v2022.10.31"
    elif [[ ! "$kak_version" < "v2022.10.31" ]]; then
        echo "source ${kak_config}/kakrc.v2022.10.31"
    else
        echo "source ${kak_config}/kakrc.old"
    fi

    # Load local settings
    # ────────────
    if [ ! -z "$DOTSLO" ] && [ -f "$DOTSLO/kak/kakrc" ]; then
        echo source "$DOTSLO/kak/kakrc"
    fi
}
